name: branch-6.0

on:
  push:
    branches: [ 6.0 ]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.202
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    # - name: Deploy GitHub Pages 🚀
    #   uses: JamesIves/github-pages-deploy-action@releases/v3
    #   with:
    #     ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    #     BRANCH: gh-pages # The branch the action should deploy to.
    #     FOLDER: src/blog/wwwroot/dist # The folder the action should deploy.
    #     SINGLE_COMMIT: false
    - name: deploy server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          sh /ga/deploy-laobian.sh stage